### ISSUE TITLE
Report as spam?

### ISSUE THREAD

**Issue by blim8183** [sarahhodne-abandoned/defender#10]
Is there a way to report a comment to Defensio as spam? I've looked through the Defender code and I'm not seeing anything.

**Comment by sarahhodne** [comment]
Not right now, it's on my todo list though.

**Comment by sarahhodne** [comment]
Ok, it's in master now. I'll push this in the next version of defender.

**Comment by sarahhodne** [comment]
This didn't quite work. See notes on commit 2f7796ac3a7bb817c29b3a90b17fb44687a21c1b.

**Comment by sarahhodne** [comment]
Ok, I think this is working in master now. Changed to using `before_create` in e2d6fae9f74908de06deb1edf7ce1f0aaeb8ef2b.
