### ISSUE TITLE
Remove InstanceMethods module

### ISSUE THREAD

**Issue by kennethlmartin** [sarahhodne-abandoned/defender#13]
This needs to be removed in order to work with rails 3.2.1

**Comment by sarahhodne** [comment]
Why? What error are you getting?

**Comment by kennethlmartin** [comment]
I kept getting an undefined method error when trying to use false_positive! or false_negative!

I took the methods out of the InstanceMethods module and put them directly in the Spammable module. I think InstanceMethods are deprecated in rails 3.2.1. After I did this it works perfectly.

Thanks for the gem btw!

**Comment by ayrton** [comment]
Did you specify the git source in your Gemfile? If not the latest gem version doesn't have these methods yet I believe. At least I didn't saw them when I `bundle open defender`'d

**Comment by sarahhodne** [comment]
The `InstanceMethods` module has nothing to do with Rails, it's a common way of including both instance methods and class methods into another module while keeping them separate. I'll investigate why there is an issue, but I don't think "removing" the `InstanceMethods` is the right way to go about solving this. Closing this for now.

**Comment by ayrton** [comment]
Just fyi, I'm using the latest stable version of Rails so 3.2.1 with the bleeding edge version of this gem and I don't have the issue that @kennethlmartin is describing.

**Comment by sarahhodne** [comment]
Thanks @ayrton. I released a new version yesterday, so there should be no reason to use the git version of the gem, either.
