### ISSUE TITLE
Mass assignment

### ISSUE THREAD

**Issue by ayrton** [sarahhodne-abandoned/defender#15]
Currently when I try to invoke the `false_positive!` method then I receive a mass assignment exception. This is because the gem is using `update_attributes`.

I'd prefer not to add the `spam` attribute in `attr_accessible` a possible solution would be to change the `update_attributes` method calls to `update_attribute`

What do you think? If you want I can make those changes and send a pull request.

**Comment by sarahhodne** [comment]
Not using `update_attributes` makes more sense. If you could send a pull request that would be stellar.
