### ISSUE TITLE
Posting fails!

### ISSUE THREAD

**Issue by conversionfoundry** [sarahhodne-abandoned/defender#2]
> > d.attributes_hash
> > => {"author-ip"=>"127.0.0.1", "author-logged-in"=>"false", "client"=>"Defender | 0.2.0 | Henrik Hodne | henrik.hodne@binaryhex.com", "type"=>"test", "author-email"=>"test@example.com", "content"=>"Test comment (no funny business)", "document-permalink"=>"http://www.leftclick.com/blog/dumb#comment_9", "parent-document-permalink"=>"http://www.leftclick.com/blog/dumb", "parent-document-date"=>"2010-01-18", "platform"=>"ruby", "author-trusted"=>"false"}
> > d.save
> > {"api-version"=>2.0, "status"=>"fail", "message"=>"The following fields are missing but required: client, content, platform, type"}
> > => false

The fields are present in the attributes_hash, so what's going on? :/

**Comment by fauxparse** [comment]
Found it! There was a problem with the arguments to HTTParty#post. I've sent a pull request for an updated version.

**Comment by sarahhodne** [comment]
Fixed in b0e4386118d49cedb4153929a96c875b40811911
