### ISSUE TITLE
Using an initializer

### ISSUE THREAD

**Issue by ngw** [sarahhodne-abandoned/defender#4]
Hi, I see I need to define my API key for every Spammable module, is there a way to use an initializer or a config file instead? Isn't it a better solution to take away configuration from the model?

**Comment by sarahhodne** [comment]
You can actually do this already. However, I do realize it's not very well documented. Create an initializer with the following code:

```
Defender.api_key = 'my_api_key'
```

I'll change the readme, this seems like a much better way to do it.

Thank you for using defender, I'm sorry I didn't get back to you before now.

**Comment by ngw** [comment]
This doesn't appear to work, test_mode seems undefined at the module level.

``` ruby
  Defender.api_key = 'FOO'
  if Rails.env == 'production'
    Defender.test_mode = false
  else
    Defender.test_mode = true
  end
```

The only way I found to do this is at the class level (inside the model)

``` ruby
  if Rails.env != 'production'
    configure_defender :api_key => 'FOO', :test_mode => true
  else
    configure_defender :api_key => 'FOO', :test_mode => false
  end
```

How can I do it?

**Comment by sarahhodne** [comment]
Split this out into a different ticket, since it's a different issue: #9.
